language: node_js

node_js:
  - "10.11.0"
  
cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

script:
  - yarn test
  - yarn build:all
    
deploy:
  provider: npm
  email: matthew.suhay@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
  
notifications:
  email:
    on_success: never
    on_failure: always