language: node_js

node_js:
  - "10.11.0"
  
cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

script:
  - yarn test
  - yarn build:all
  
notifications:
  email:
    on_success: never
    on_failure: always