language: node_js

node_js:
  - "12.7.0"
  
cache: yarn

script:
  - yarn
  - yarn test
  - yarn build:all
    
deploy:
  provider: script
  script: yarn publish:push
  email: matthew.suhay@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
  
notifications:
  email:
    on_success: never
    on_failure: always