---
title: 'New ReactY Page' # Title of the page, will be used to create URL if not slug is supplied
slug: '' # optional, used for URL creation URL

# Meta data objects. A single key value pair will set the key as the value for 'name='
# and the value will be used as the value for 'content='.
# Multiple key value pairs will follow the key=value pattern
meta:
  - httpEquiv: 'X-UA-Compatible'
    content: 'IE=edge'
  - charSet: 'UTF-8'
  - viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no'
  
# meta description of page, content will be used if left blank
description: 'This is a base ReactY page'

page:
  header: ''
  main: ''
  footer: ''
  
# Internal tags used for relating content to eachother
tags: []

# Single string will load the value as the script's src.
#  - 'https://example.com/script.js'
#
# Adding 'async' or 'defer' to the scripts will output the attribute
#  - 'https://example.com/script.js'
#    - async
#    - defer

scripts: []
headScripts: []

links:
  # Single string will load the value as href
  - 'https://fonts.googleapis.com/css?family=Montserrat:200,300,400,700,900'
  # For complex links, the key is used as the attribute name and the value is its value
  # <link key="value" />
  - href: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' 
    integrity: "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin: "anonymous"