---
title: Page Title # Title of the page, will be used to create URL if not slug is supplied
slug: '' # Optional, used for URL creation URL 'subsite/subsite/page'
meta: [] # Meta data objects
description: '' # Meta description of page, content will be used if left blank
content:
  header: '' # Pull in all the tags and loop over them (typing out)
  main: ''
  footer: ''
tags: []
scripts: []
links: []