export { default as Col } from './col'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Main } from './main'
export { default as Section } from './section'
